version: '3.3'
services:

  frontend_foodgram:
    image: potesuch/foodgram-project-react-frontend
    volumes:
      - frontend_foodgram:/app/result_build/
  db_foodgram:
    image: postgres:13.0-alpine
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_foodgram:/var/lib/postgresql/data/
    env_file:
      - ./.env
  backendfoodgram:
    image: potesuch/foodgram-project-react-backend
    ports:
      - "8003:8000"
    volumes:
      - static_value_foodgram:/app/static/
      - media_value_foodgram:/app/media/
    env_file:
      - ./.env
    depends_on:
      - db_foodgram
  nginx_foodgram:
    image: nginx:1.19.3
    ports:
      - "84:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value_foodgram:/var/html/static/
      - media_value_foodgram:/var/html/media/
    depends_on:
      - backendfoodgram

volumes:
  frontend_foodgram:
  static_value_foodgram:
  media_value_foodgram:
  postgres_data_foodgram:
